#cloud-config
users:
  - name: slurm
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users
    home: /home/slurm
    shell: /bin/bash
    lock_passwd: false
    passwd: $6$rounds=4096$randomsalt$hashedpassword

runcmd:
  - dnf update -y
  - dnf install -y python3 python3-pip git
  - pip3 install ansible
  - git clone https://github.com/your-repo/your-playbook-repo.git /etc/ansible/playbook-repo
  - ansible-playbook /etc/ansible/playbook-repo/ecc-setup.yml
