---
- hosts: all
  become: yes
  tasks:
    - name: Update all packages (APT)
      apt:
        update_cache: yes
        upgrade: dist
      when: ansible_pkg_mgr == "apt"

    - name: Update all packages (DNF)
      dnf:
        update_cache: yes
        state: latest
      when: ansible_pkg_mgr == "dnf"

    - name: Install required packages (APT)
      apt:
        name:
          - python3
          - python3-pip
          - slurm-wlm
        state: present
      when: ansible_pkg_mgr == "apt"

    - name: Install required packages (DNF)
      dnf:
        name:
          - python3
          - python3-pip
          - slurm
        state: present
      when: ansible_pkg_mgr == "dnf"

    - name: Enable and start slurmd service
      systemd:
        name: slurmd
        enabled: yes
        state: started
